const express = require('express');
const path = require('path');
const fs = require('fs');
const { execFile } = require('child_process');
const { promisify } = require('util');

const execFileAsync = promisify(execFile);

const app = express();

const PORT = 38127;

const REQUEST_BODY_LIMIT = '1kb';
const MAX_CONCURRENT_GENERATIONS = 10;
const RATE_LIMIT_WINDOW_MS = 5 * 60 * 1000;
const RATE_LIMIT_MAX_REQUESTS = 10;
const MAX_CSS_SIZE_BYTES = 0.5 * 1024 * 1024;

let activeGenerations = 0;
const requestCounts = new Map();

const ROOT_DIR = __dirname;

const NODE_MODULES = path.join(
    ROOT_DIR,
    'node_modules'
);

const TEMPLATE_FILE = path.join(
    ROOT_DIR,
    'templates',
    '_customized-theme.scss'
);

const IMPORT_COMMENT = `/*
 * Import this file into your main custom.css so you don't have to copy and paste 
 * everything into one file. Make sure that this file is placed in the same directory
 * as your main custom.css file and add the following line to your custom.css file:
 * [Note: you can change the name of the file if you want, just make sure to update the import statement accordingly.]
 * 
 * 
 * @import url("customized-theme.css");
 *
 * Place the @import statement near the top of custom.css,
 * before other CSS rules.
 */


`;

const FINAL_NOTE = `

/*
 * This file was generated by the PASCAL NDE Theme Generator.
 * It contains the Angular Material theme CSS created from the
 * colors selected in the generator.
 * You can edit this file directly, or generate a new theme by using the generator again.
 */
`;

const WORK_DIR = path.join(
    ROOT_DIR,
    'work'
);


/*
 * Middleware
 */

app.disable('x-powered-by');

app.use((req, res, next) => {

    res.setHeader(
        'Content-Security-Policy',
        "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'"
    );
    res.setHeader('Referrer-Policy', 'no-referrer');
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('X-Frame-Options', 'DENY');
    res.setHeader('Cross-Origin-Resource-Policy', 'same-origin');

    next();

});

app.use(express.json({
    limit: REQUEST_BODY_LIMIT,
    strict: true
}));

app.use(
    express.static(
        path.join(ROOT_DIR, 'public')
    )
);


/*
 * Make sure work directory exists
 */

fs.mkdirSync(
    WORK_DIR,
    {
        recursive: true
    }
);


/*
 * Validate colors
 */

function isValidColor(value) {

    return (
        typeof value === 'string' &&
        /^#[0-9a-fA-F]{6}$/.test(value)
    );

}

function isValidOptionalColor(value) {
    return (
        value == null ||
        isValidColor(value)
    );
}


/*
 * Generate theme
 */

app.post('/generate-theme', async (req, res) => {

    const now = Date.now();

    for (const [address, requestWindow] of requestCounts) {

        if (requestWindow.expiresAt <= now) {
            requestCounts.delete(address);
        }

    }

    const clientAddress = req.ip || req.socket.remoteAddress || 'unknown';
    const previousRequests = requestCounts.get(clientAddress);
    const requestWindow = previousRequests &&
        previousRequests.expiresAt > now
        ? previousRequests
        : {
            count: 0,
            expiresAt: now + RATE_LIMIT_WINDOW_MS
        };

    requestWindow.count += 1;
    requestCounts.set(clientAddress, requestWindow);

    if (requestWindow.count > RATE_LIMIT_MAX_REQUESTS) {

        res.setHeader('Retry-After', String(Math.ceil(
            (requestWindow.expiresAt - now) / 1000
        )));

        return res
            .status(429)
            .send('Too many generation requests. Please try again later.');

    }

    if (activeGenerations >= MAX_CONCURRENT_GENERATIONS) {

        return res
            .status(503)
            .send('Theme generation is busy. Please try again shortly.');

    }

    activeGenerations += 1;

    const {
        primary,
        secondary,
        tertiary,
        neutral
    } = req.body;


    /*
     * Validate input
     */

    if (
        !req.body ||
        Array.isArray(req.body) ||
		!isValidColor(primary) ||
		!isValidOptionalColor(secondary) ||
		!isValidOptionalColor(tertiary) ||
		!isValidOptionalColor(neutral)
	) {
        activeGenerations -= 1;

		return res
			.status(400)
			.send('Invalid color value.');
	}


    let tempDir = null;


    try {

        /*
         * Create a unique temporary directory
         * INSIDE the Angular workspace
         */

        tempDir = fs.mkdtempSync(
            path.join(
                WORK_DIR,
                'm3-theme-'
            )
        );


        /*
         * Angular wants --directory to be
         * relative to the workspace.
         */

		const relativeTempDir = path
			.relative(ROOT_DIR, tempDir)
			.replace(/\\/g, '/') + '/';
			
			


        /*
         * Angular CLI JavaScript entrypoint
         */

        const ngPath = path.join(
            ROOT_DIR,
            'node_modules',
            '@angular',
            'cli',
            'bin',
            'ng.js'
        );

		console.log('Generating theme in:', relativeTempDir);
        /*
         * Generate m3-theme.scss
         */

        const ngArgs = [

			ngPath,

			'generate',
			'@angular/material:m3-theme',

			'--primary-color',
			primary,

			'--theme-types',
			'both',

			'--use-system-variables',

			'--interactive',
			'false',

			'--force',

			'--directory',
			relativeTempDir

		];


		if (secondary) {

			ngArgs.push(
				'--secondary-color',
				secondary
			);

		}


		if (tertiary) {

			ngArgs.push(
				'--tertiary-color',
				tertiary
			);

		}


		if (neutral) {

			ngArgs.push(
				'--neutral-color',
				neutral
			);

		}


		await execFileAsync(
			process.execPath,
			ngArgs,
			{
				cwd: ROOT_DIR,
                timeout: 30000,
                maxBuffer: 1024 * 1024,
                windowsHide: true
			}
		);

		const themePath = path.join(
			tempDir,
			'm3-theme.scss'
		);

		if (!fs.existsSync(themePath)) {
			throw new Error(
				`Angular did not create expected theme file: ${themePath}`
			);
		}
		console.log('Theme file created:', themePath);

        /*
         * Copy wrapper SCSS into temp directory
         */

        const wrapperPath = path.join(
            tempDir,
            '_customized-theme.scss'
        );

        fs.copyFileSync(
            TEMPLATE_FILE,
            wrapperPath
        );


        /*
         * Sass JavaScript entrypoint
         */

        const sassPath = path.join(
            ROOT_DIR,
            'node_modules',
            'sass',
            'sass.js'
        );


        /*
         * CSS output path
         */

        const cssPath = path.join(
            tempDir,
            'customized-theme.css'
        );


        /*
         * Compile SCSS into CSS
         */

        await execFileAsync(
            process.execPath,
            [
                sassPath,

                '--load-path',
                NODE_MODULES,

                wrapperPath,

                cssPath,

                '--style=expanded',

                '--no-source-map'
            ],
            {
                cwd: tempDir,
                timeout: 30000,
                maxBuffer: 1024 * 1024,
                windowsHide: true
            }
        );

        if (fs.statSync(cssPath).size > MAX_CSS_SIZE_BYTES) {
            throw new Error('Generated CSS exceeds the permitted size.');
        }


        /*
         * Read CSS into memory
         */

        const generatedCss = fs.readFileSync(
            cssPath,
            'utf8'
        );

        const css = IMPORT_COMMENT + generatedCss + FINAL_NOTE;


        /*
         * Delete temp files
         */

        fs.rmSync(
            tempDir,
            {
                recursive: true,
                force: true
            }
        );

        tempDir = null;


        /*
         * Return CSS file
         */

        res.setHeader(
            'Content-Type',
            'text/css'
        );

        res.setHeader(
            'Cache-Control',
            'no-store'
        );

        res.setHeader(
            'Content-Disposition',
            'attachment; filename="customized-theme.css"'
        );

        res.send(css);

    }
    catch (error) {

        console.error(error);


        /*
         * Clean temp directory if something failed
         */

        if (tempDir) {

            try {

                fs.rmSync(
                    tempDir,
                    {
                        recursive: true,
                        force: true
                    }
                );

            }
            catch (cleanupError) {

                console.error(
                    'Cleanup failed:',
                    cleanupError
                );

            }

        }


        res
            .status(500)
            .send('Unable to generate theme.');

    }
    finally {

        activeGenerations -= 1;

    }

});


/*
 * Keep parser and unexpected errors from exposing framework details.
 */

app.use((error, req, res, next) => {

    if (res.headersSent) {
        return next(error);
    }

    if (error.type === 'entity.too.large') {
        return res
            .status(413)
            .send('Request body is too large.');
    }

    if (error.type === 'entity.parse.failed') {
        return res
            .status(400)
            .send('Invalid JSON request.');
    }

    console.error(error);

    return res
        .status(500)
        .send('Internal server error.');

});


/*
 * Start server
 */

app.listen(
    PORT,
    '127.0.0.1',
    () => {

        console.log(
            `Theme generator running at http://127.0.0.1:${PORT}`
        );

    }
);
